# Generated by Django 4.1.5 on 2023-02-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petID', models.IntegerField(primary_key=True, serialize=False)),
                ('petName', models.CharField(max_length=50)),
                ('lastFed', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerUser',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('petID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekozumi_app.pet')),
            ],
        ),
    ]
