# Generated by Django 4.1.5 on 2023-02-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekozumi_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playeruser',
            old_name='username',
            new_name='USERNAME_FIELD',
        ),
        migrations.AlterField(
            model_name='playeruser',
            name='petID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ekozumi_app.pet'),
        ),
    ]
