# Generated by Django 4.1.5 on 2023-03-09 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ekozumi_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monster",
            old_name="mosterID",
            new_name="monsterID",
        ),
        migrations.AlterField(
            model_name="pet",
            name="lastFed",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 9, 16, 58, 6, 333491, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
