# Generated by Django 4.1.5 on 2023-03-09 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekozumi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='lastFed',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 14, 5, 43, 233614, tzinfo=datetime.timezone.utc)),
        ),
    ]
