# Generated by Django 4.1.5 on 2023-03-20 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekozumi_app', '0002_megaboss_alter_pet_lastfed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='lastFed',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 15, 11, 58, 654323, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pet',
            name='petType',
            field=models.CharField(choices=[('Hedgehog', 'Hedgehog'), ('Fox', 'Fox'), ('Frog', 'Frog'), ('Rabbit', 'Rabbit'), ('Bluetit', 'Bluetit')], max_length=9),
        ),
    ]
