# Generated by Django 4.1.5 on 2023-03-16 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekozumi_app', '0003_alter_pet_lastfed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='lastFed',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 11, 39, 54, 642527, tzinfo=datetime.timezone.utc)),
        ),
    ]
