# Generated by Django 4.1.5 on 2023-02-23 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekozumi_app', '0007_alter_pet_lastfed_alter_pet_pettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='lastFed',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 11, 35, 30, 368284, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pet',
            name='petType',
            field=models.CharField(max_length=9),
        ),
    ]
