# Generated by Django 4.1.5 on 2023-02-23 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekozumi_app', '0009_alter_pet_lastfed_alter_pet_pettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='lastFed',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 13, 8, 20, 125511, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pet',
            name='petID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
